### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by atmchuck** [tdietrich513/DataTableProxy#1]
Tom,
First, thanks for sharing this. I was able to get things working very quickly. However, in my particular scenario, I'm attempting to put the results of the ToTable() method into the DataSource of a Recordset, and I get the exception System.InvalidCastException("No such interface supported"). I have a snippet of my code below.
Any help is appreciated.
Thanks,
Chuck

var rs = new ADOR.Recordset();
var repo = new CustomerRepository<CustomerRepositoryContext>();
//The following line threw the exception, so I broke it apart below
//rs.DataSource = repo.GetInfo(pId).ToTable(new ClassMapping<Account>().AddAllPropertiesAsColumns());

//This is the one line of code broken apart
var accountList = repository.GetInfo(pId);
var classMapping = new ClassMapping<Account>().AddAllPropertiesAsColumns();
var table = accountList.ToTable(classMapping);
rs.DataSource = table; //Exception is thrown on this line

**Comment by atmchuck** [comment]
Tom,
I found the error of my ways. I was able to Convert the DataTable you return into a Recordset using the info at the following link; http://www.codeproject.com/Articles/10503/Simplest-code-to-convert-an-ADO-NET-DataTable-to-a

If there is something I'm missing that you are already natively supplying, please let me know. Again, thanks for sharing what you did with the DataTableProxy.
Regards,
Chuck

**Comment by tdietrich513** [comment]
Glad you were able to figure it out!
