### ISSUE TITLE
Referenced assembly "DataTableProxy, Version=1.1.0.0, Culture=neutral, PublicKeyToken=off

### ISSUE THREAD

**Issue by sej69** [tdietrich513/DataTableProxy#5]
I've got a signed application that I'd like to try linking this project into.  Any chance of signing it (even with a self-signed cert)?

**Comment by tdietrich513** [comment]
Really no plans to do that, but do feel free to copy and paste the 4 .cs files that make up this package into your application, no need to even credit me. This code is open and free for redistribution in binary and source format. You just need 

1. ClassMapping.cs
2. ColumnMapping.cs
3. DataTableProxy.cs
4. EnumerableExtensions.cs (optional, just if you want them really)
